site_name: vcfanno
site_url: https://github.com/brentp/vcfanno
repo_url: https://github.com/brentp/vcfanno
pages:
- Home: index.md
- Performance: performance_tips.md
- Changes: CHANGES.md
- Examples:
    - ClinvarExac: examples/clinvar_exac.md
    - CADD: examples/cadd.md
    - ExAC-Combine: examples/exac_combine/exac_combine.md
theme: cinder

